version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  assignees:
  - bestony
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.8.0
  - dependency-name: stylus-loader
    versions:
    - 4.3.3
